config/routes.rb
LithiumPoc::Application.routes.draw do
  resources :archived_telematics_data

  resources :current_telematics_data

  resources :shifts

  namespace :api, defaults: { format: 'json' } do
    namespace :v1 do
      resources :shifts do
        collection do
          get 'index'
        end
      end

      resources :trips do
        member do
          get 'show'
        end
      end

      resources :trip_summaries do
        member do
          post 'create'
        end
      end
    end
  end

  resources :archived_vehicle_positions
  resources :current_vehicle_positions
  resources :trip_summaries
  resources :trips
  resources :vehicles

  root "pages#home"
  get "home", to: "pages#home", as: "home"
  get "inside", to: "pages#inside", as: "inside"

  devise_for :users

  namespace :admin do
    root "base#index"
    resources :users

  end

end

app/models/archived_vehicle_position.rb
class ArchivedVehiclePosition < ActiveRecord::Base
  belongs_to :vehicle
  belongs_to :telematics_data, class_name: "ArchivedTelematicsData", foreign_key: "telematics_data_id"
end

app/controllers/archived_vehicle_positions_controller.rb
class ArchivedVehiclePositionsController < ApplicationController
  before_action :set_archived_vehicle_position, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @archived_vehicle_positions = ArchivedVehiclePosition.all
    respond_with(@archived_vehicle_positions)
  end

  def show
    respond_with(@archived_vehicle_position)
  end

  def new
    @archived_vehicle_position = ArchivedVehiclePosition.new
    respond_with(@archived_vehicle_position)
  end

  def edit
  end

  def create
    @archived_vehicle_position = ArchivedVehiclePosition.new(archived_vehicle_position_params)
    @archived_vehicle_position.save
    respond_with(@archived_vehicle_position)
  end

  def update
    @archived_vehicle_position.update(archived_vehicle_position_params)
    respond_with(@archived_vehicle_position)
  end

  def destroy
    @archived_vehicle_position.destroy
    respond_with(@archived_vehicle_position)
  end

  private
    def set_archived_vehicle_position
      @archived_vehicle_position = ArchivedVehiclePosition.find(params[:id])
    end

    def archived_vehicle_position_params
      params.require(:archived_vehicle_position).permit(:vehicle_id, :trip_id, :curr_lat, :curr_lon, :curr_timestamp, :prev_lat, :prev_lon, :heading, :speed, :altitude, :accuracy, :soc, :dte, :odometer_reading, :distance_from_previous, :distance_covered)
    end
end

app/helpers/archived_vehicle_positions_helper.rb
module ArchivedVehiclePositionsHelper
end

app/views/archived_vehicle_positions/_form.html.erb
<%= form_for(@archived_vehicle_position) do |f| %>
  <% if @archived_vehicle_position.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@archived_vehicle_position.errors.count, "error") %> prohibited this archived_vehicle_position from being saved:</h2>

      <ul>
      <% @archived_vehicle_position.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :vehicle_id %><br>
    <%= f.number_field :vehicle_id %>
  </div>
  <div class="field">
    <%= f.label :trip_id %><br>
    <%= f.number_field :trip_id %>
  </div>
  <div class="field">
    <%= f.label :curr_lat %><br>
    <%= f.text_field :curr_lat %>
  </div>
  <div class="field">
    <%= f.label :curr_lon %><br>
    <%= f.text_field :curr_lon %>
  </div>
  <div class="field">
    <%= f.label :curr_timestamp %><br>
    <%= f.datetime_select :curr_timestamp %>
  </div>
  <div class="field">
    <%= f.label :prev_lat %><br>
    <%= f.text_field :prev_lat %>
  </div>
  <div class="field">
    <%= f.label :prev_lon %><br>
    <%= f.text_field :prev_lon %>
  </div>
  <div class="field">
    <%= f.label :heading %><br>
    <%= f.text_field :heading %>
  </div>
  <div class="field">
    <%= f.label :speed %><br>
    <%= f.text_field :speed %>
  </div>
  <div class="field">
    <%= f.label :altitude %><br>
    <%= f.text_field :altitude %>
  </div>
  <div class="field">
    <%= f.label :accuracy %><br>
    <%= f.text_field :accuracy %>
  </div>
  <div class="field">
    <%= f.label :soc %><br>
    <%= f.text_field :soc %>
  </div>
  <div class="field">
    <%= f.label :dte %><br>
    <%= f.text_field :dte %>
  </div>
  <div class="field">
    <%= f.label :odometer_reading %><br>
    <%= f.text_field :odometer_reading %>
  </div>
  <div class="field">
    <%= f.label :distance_from_previous %><br>
    <%= f.text_field :distance_from_previous %>
  </div>
  <div class="field">
    <%= f.label :distance_covered %><br>
    <%= f.text_field :distance_covered %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/archived_vehicle_positions/edit.html.erb
<h1>Editing archived_vehicle_position</h1>

<%= render 'form' %>

<%= link_to 'Show', @archived_vehicle_position %> |
<%= link_to 'Back', archived_vehicle_positions_path %>

app/views/archived_vehicle_positions/index.html.erb
<h1>Listing archived_vehicle_positions</h1>

<table>
  <thead>
    <tr>
      <th>Vehicle</th>
      <th>Trip</th>
      <th>Curr lat</th>
      <th>Curr lon</th>
      <th>Curr timestamp</th>
      <th>Prev lat</th>
      <th>Prev lon</th>
      <th>Heading</th>
      <th>Speed</th>
      <th>Altitude</th>
      <th>Accuracy</th>
      <th>Soc</th>
      <th>Dte</th>
      <th>Odometer reading</th>
      <th>Distance from previous</th>
      <th>Distance covered</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @archived_vehicle_positions.each do |archived_vehicle_position| %>
      <tr>
        <td><%= archived_vehicle_position.vehicle_id %></td>
        <td><%= archived_vehicle_position.trip_id %></td>
        <td><%= archived_vehicle_position.curr_lat %></td>
        <td><%= archived_vehicle_position.curr_lon %></td>
        <td><%= archived_vehicle_position.curr_timestamp %></td>
        <td><%= archived_vehicle_position.prev_lat %></td>
        <td><%= archived_vehicle_position.prev_lon %></td>
        <td><%= archived_vehicle_position.heading %></td>
        <td><%= archived_vehicle_position.speed %></td>
        <td><%= archived_vehicle_position.altitude %></td>
        <td><%= archived_vehicle_position.accuracy %></td>
        <td><%= archived_vehicle_position.soc %></td>
        <td><%= archived_vehicle_position.dte %></td>
        <td><%= archived_vehicle_position.odometer_reading %></td>
        <td><%= archived_vehicle_position.distance_from_previous %></td>
        <td><%= archived_vehicle_position.distance_covered %></td>
        <td><%= link_to 'Show', archived_vehicle_position %></td>
        <td><%= link_to 'Edit', edit_archived_vehicle_position_path(archived_vehicle_position) %></td>
        <td><%= link_to 'Destroy', archived_vehicle_position, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Archived vehicle position', new_archived_vehicle_position_path %>

app/views/archived_vehicle_positions/new.html.erb
<h1>New archived_vehicle_position</h1>

<%= render 'form' %>

<%= link_to 'Back', archived_vehicle_positions_path %>

app/views/archived_vehicle_positions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Vehicle:</strong>
  <%= @archived_vehicle_position.vehicle_id %>
</p>

<p>
  <strong>Trip:</strong>
  <%= @archived_vehicle_position.trip_id %>
</p>

<p>
  <strong>Curr lat:</strong>
  <%= @archived_vehicle_position.curr_lat %>
</p>

<p>
  <strong>Curr lon:</strong>
  <%= @archived_vehicle_position.curr_lon %>
</p>

<p>
  <strong>Curr timestamp:</strong>
  <%= @archived_vehicle_position.curr_timestamp %>
</p>

<p>
  <strong>Prev lat:</strong>
  <%= @archived_vehicle_position.prev_lat %>
</p>

<p>
  <strong>Prev lon:</strong>
  <%= @archived_vehicle_position.prev_lon %>
</p>

<p>
  <strong>Heading:</strong>
  <%= @archived_vehicle_position.heading %>
</p>

<p>
  <strong>Speed:</strong>
  <%= @archived_vehicle_position.speed %>
</p>

<p>
  <strong>Altitude:</strong>
  <%= @archived_vehicle_position.altitude %>
</p>

<p>
  <strong>Accuracy:</strong>
  <%= @archived_vehicle_position.accuracy %>
</p>

<p>
  <strong>Soc:</strong>
  <%= @archived_vehicle_position.soc %>
</p>

<p>
  <strong>Dte:</strong>
  <%= @archived_vehicle_position.dte %>
</p>

<p>
  <strong>Odometer reading:</strong>
  <%= @archived_vehicle_position.odometer_reading %>
</p>

<p>
  <strong>Distance from previous:</strong>
  <%= @archived_vehicle_position.distance_from_previous %>
</p>

<p>
  <strong>Distance covered:</strong>
  <%= @archived_vehicle_position.distance_covered %>
</p>

<%= link_to 'Edit', edit_archived_vehicle_position_path(@archived_vehicle_position) %> |
<%= link_to 'Back', archived_vehicle_positions_path %>