config/routes.rb
LithiumPoc::Application.routes.draw do
  resources :archived_telematics_data

  resources :current_telematics_data

  resources :shifts

  namespace :api, defaults: { format: 'json' } do
    namespace :v1 do
      resources :shifts do
        collection do
          get 'index'
        end
      end

      resources :trips do
        member do
          get 'show'
        end
      end

      resources :trip_summaries do
        member do
          post 'create'
        end
      end
    end
  end

  resources :archived_vehicle_positions
  resources :current_vehicle_positions
  resources :trip_summaries
  resources :trips
  resources :vehicles

  root "pages#home"
  get "home", to: "pages#home", as: "home"
  get "inside", to: "pages#inside", as: "inside"

  devise_for :users

  namespace :admin do
    root "base#index"
    resources :users

  end

end

app/models/trip_summary.rb
class TripSummary < ActiveRecord::Base
  belongs_to :trip

  def delta
    {
      trip_id: trip_id,
      trip_summary_id: id,
      deviation_in_soc: trip.estimated_soc_difference - actual_soc_difference,
      deviation_in_distance: trip.estimated_distance - distance,
      deviation_in_travel_duration: trip.estimated_travel_duration - actual_travel_duration
    }
  end

  def actual_soc_difference
    start_soc - end_soc
  end

  def actual_travel_duration
    time_of_departure - time_of_arrival
  end
end

app/controllers/api/v1/trip_summaries_controller.rb
module Api
  module V1
    class TripSummariesController < ApplicationController
      skip_before_filter :verify_authenticity_token

      respond_to :json

      # SAMPLE calls
      # http://localhost:3000/api/v1/trip_summaries?summary[trip_id]=1&summary[distance]=25&summary[time_of_departure]=9:00&summary[time_of_arrival]=10:30&summary[start_soc]=85&summary[end_soc]=60&summary[average_speed]=12 =>
      # Create trip-summary
      # POST
      def create
        Rails.logger.debug "API DEBUG: trip_summaries#create: #{params}"

        trip_summary = TripSummary.new(params.require(:summary).permit(:trip_id, :distance, :time_of_departure,
          :time_of_arrival, :start_soc, :end_soc, :average_speed))

        begin
          if trip_summary.save
            render json: trip_summary.delta, status: :ok
          else
            errors = trip_summary.errors
            render json: errors.to_json, status: 400
          end
        rescue
          errors = "Exception"
          render json: errors.to_json, status: 400
        end

      end
    end
  end
end

app/controllers/trip_summaries_controller.rb
class TripSummariesController < ApplicationController
  before_action :set_trip_summary, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @trip_summaries = TripSummary.all
    respond_with(@trip_summaries)
  end

  def show
    respond_with(@trip_summary)
  end

  def new
    @trip_summary = TripSummary.new
    respond_with(@trip_summary)
  end

  def edit
  end

  def create
    @trip_summary = TripSummary.new(trip_summary_params)
    @trip_summary.save
    respond_with(@trip_summary)
  end

  def update
    @trip_summary.update(trip_summary_params)
    respond_with(@trip_summary)
  end

  def destroy
    @trip_summary.destroy
    respond_with(@trip_summary)
  end

  private
    def set_trip_summary
      @trip_summary = TripSummary.find(params[:id])
    end

    def trip_summary_params
      params.require(:trip_summary).permit(:trip_id, :distance, :time_of_departure, :time_of_arrival, :start_soc, :end_soc, :average_speed)
    end
end

app/helpers/trip_summaries_helper.rb
module TripSummariesHelper
end

app/views/trip_summaries/_form.html.erb
<%= form_for @trip_summary, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="form-group">
    <%= f.label :trip_id, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :trip_id, :class => 'text_field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :distance, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :distance, :class => 'text_field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :time_of_departure, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :time_of_departure, :class => 'text_field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :time_of_arrival, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :time_of_arrival, :class => 'text_field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :start_soc, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :start_soc, :class => 'text_field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :end_soc, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :end_soc, :class => 'text_field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :average_speed, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :average_speed, :class => 'text_field form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class='col-md-offset-2 col-md-10'>
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  trip_summaries_path, :class => 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/trip_summaries/edit.html.erb
<%- model_class = TripSummary -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/trip_summaries/index.html.erb
<%- model_class = TripSummary -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:trip_id) %></th>
      <th><%= model_class.human_attribute_name(:distance) %></th>
      <th><%= model_class.human_attribute_name(:time_of_departure) %></th>
      <th><%= model_class.human_attribute_name(:time_of_arrival) %></th>
      <th><%= model_class.human_attribute_name(:start_soc) %></th>
      <th><%= model_class.human_attribute_name(:end_soc) %></th>
      <th><%= model_class.human_attribute_name(:average_speed) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @trip_summaries.each do |trip_summary| %>
      <tr>
        <td><%= trip_summary.id %></td>
          <td><%= trip_summary.trip_id %></td>
          <td><%= trip_summary.distance %></td>
          <td><%= trip_summary.time_of_departure %></td>
          <td><%= trip_summary.time_of_arrival %></td>
          <td><%= trip_summary.start_soc %></td>
          <td><%= trip_summary.end_soc %></td>
          <td><%= trip_summary.average_speed %></td>
        <td><%=l trip_summary.created_at, format: :long %></td>
        <td>
          <%= link_to trip_summary_path(trip_summary), :class => 'btn btn-xs', :title => "#{ t('.show', :default => t('helpers.links.show')) }" do %>
            <%= glyph 'info-sign' %>
          <%- end -%>
          <%= link_to edit_trip_summary_path(trip_summary), :class => 'btn btn-xs', :title => "#{ t('.edit', :default => t('helpers.links.edit')) }" do %>
            <%= glyph 'pencil' %>
          <%- end -%>
          <%= link_to trip_summary_path(trip_summary), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs', :title => "#{ t('.destroy', :default => t('helpers.links.destroy')) }" do %>
            <%= glyph 'remove' %>
          <%- end -%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_trip_summary_path,
            :class => 'btn btn-primary' %>

app/views/trip_summaries/new.html.erb
<%- model_class = TripSummary -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/trip_summaries/show.html.erb
<%- model_class = TripSummary -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<div class="fieldset">
  <dl>
      <dt class="label label-default"><%= model_class.human_attribute_name(:trip_id) %></dt>
      <dd><pre class="prettyprint"><%= @trip_summary.trip_id %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:distance) %></dt>
      <dd><pre class="prettyprint"><%= @trip_summary.distance %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:time_of_departure) %></dt>
      <dd><pre class="prettyprint"><%= @trip_summary.time_of_departure %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:time_of_arrival) %></dt>
      <dd><pre class="prettyprint"><%= @trip_summary.time_of_arrival %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:start_soc) %></dt>
      <dd><pre class="prettyprint"><%= @trip_summary.start_soc %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:end_soc) %></dt>
      <dd><pre class="prettyprint"><%= @trip_summary.end_soc %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:average_speed) %></dt>
      <dd><pre class="prettyprint"><%= @trip_summary.average_speed %></pre></dd>
  </dl>
</div>

<div class="form-group">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              trip_summaries_path, :class => 'btn btn-default'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_trip_summary_path(@trip_summary), :class => 'btn btn-default' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              trip_summary_path(@trip_summary),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>