config/routes.rb
LithiumPoc::Application.routes.draw do
  resources :archived_telematics_data

  resources :current_telematics_data

  resources :shifts

  namespace :api, defaults: { format: 'json' } do
    namespace :v1 do
      resources :shifts do
        collection do
          get 'index'
        end
      end

      resources :trips do
        member do
          get 'show'
        end
      end

      resources :trip_summaries do
        member do
          post 'create'
        end
      end
    end
  end

  resources :archived_vehicle_positions
  resources :current_vehicle_positions
  resources :trip_summaries
  resources :trips
  resources :vehicles

  root "pages#home"
  get "home", to: "pages#home", as: "home"
  get "inside", to: "pages#inside", as: "inside"

  devise_for :users

  namespace :admin do
    root "base#index"
    resources :users

  end

end

app/models/vehicle.rb
class Vehicle < ActiveRecord::Base
  has_many :trips
  has_one :current_vehicle_position
  has_many :archived_vehicle_positions

  has_one :current_telematics_datum
  has_many :archived_telematics_data
end

app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController
  before_action :set_vehicle, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @vehicles = Vehicle.all
    respond_with(@vehicles)
  end

  def show
    respond_with(@vehicle)
  end

  def new
    @vehicle = Vehicle.new
    respond_with(@vehicle)
  end

  def edit
  end

  def create
    @vehicle = Vehicle.new(vehicle_params)
    @vehicle.save
    respond_with(@vehicle)
  end

  def update
    @vehicle.update(vehicle_params)
    respond_with(@vehicle)
  end

  def destroy
    @vehicle.destroy
    respond_with(@vehicle)
  end

  private
    def set_vehicle
      @vehicle = Vehicle.find(params[:id])
    end

    def vehicle_params
      params.require(:vehicle).permit(:name, :registration_number, :vin_number)
    end
end

app/helpers/vehicles_helper.rb
module VehiclesHelper
end

app/views/vehicles/_form.html.erb
<%= form_for @vehicle, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :name, :class => 'text_field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :registration_number, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :registration_number, :class => 'text_field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :vin_number, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :vin_number, :class => 'text_field form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class='col-md-offset-2 col-md-10'>
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  vehicles_path, :class => 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/vehicles/edit.html.erb
<%- model_class = Vehicle -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/vehicles/index.html.erb
<%- model_class = Vehicle -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:registration_number) %></th>
      <th><%= model_class.human_attribute_name(:vin_number) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @vehicles.each do |vehicle| %>
      <tr>
        <td><%= vehicle.id %></td>
          <td><%= vehicle.name %></td>
          <td><%= vehicle.registration_number %></td>
          <td><%= vehicle.vin_number %></td>
        <td><%=l vehicle.created_at, format: :long %></td>
        <td>
          <%= link_to vehicle_path(vehicle), :class => 'btn btn-xs', :title => "#{ t('.show', :default => t('helpers.links.show')) }" do %>
            <%= glyph 'info-sign' %>
          <%- end -%>
          <%= link_to edit_vehicle_path(vehicle), :class => 'btn btn-xs', :title => "#{ t('.edit', :default => t('helpers.links.edit')) }" do %>
            <%= glyph 'pencil' %>
          <%- end -%>
          <%= link_to vehicle_path(vehicle), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs', :title => "#{ t('.destroy', :default => t('helpers.links.destroy')) }" do %>
            <%= glyph 'remove' %>
          <%- end -%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_vehicle_path,
            :class => 'btn btn-primary' %>

app/views/vehicles/new.html.erb
<%- model_class = Vehicle -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/vehicles/show.html.erb
<%- model_class = Vehicle -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<div class="fieldset">
  <dl>
      <dt class="label label-default"><%= model_class.human_attribute_name(:name) %></dt>
      <dd><pre class="prettyprint"><%= @vehicle.name %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:registration_number) %></dt>
      <dd><pre class="prettyprint"><%= @vehicle.registration_number %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:vin_number) %></dt>
      <dd><pre class="prettyprint"><%= @vehicle.vin_number %></pre></dd>
  </dl>
</div>

<div class="form-group">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              vehicles_path, :class => 'btn btn-default'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_vehicle_path(@vehicle), :class => 'btn btn-default' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              vehicle_path(@vehicle),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>